### ISSUE TITLE
Setting initial picker value not working properly

### ISSUE THREAD

**Issue by alexandre-g** [kronik/ScalePicker#1]
`setInitialCurrentValue(value: CGFloat)` sets the value and the picker loads with that value selected, but then animates to 0 straight away.

**Comment by alexandre-g** [comment]
And it happens because of this genius code here:

```
dispatch_after(dispatch_time(DISPATCH_TIME_NOW, Int64(0.5 * CGFloat(NSEC_PER_SEC))), dispatch_get_main_queue()) {
            self.setInitialCurrentValue(0.0)
        }
```

**Comment by kronik** [comment]
Actually that was intentionally in our app. Moved current value initialization outside of control.
