### ISSUE TITLE
Set Initial Value Does Not Work With Decimals

### ISSUE THREAD

**Issue by chrisfoulds** [kronik/ScalePicker#3]
I have my ScalePicker setup to be between 0-400
I have it so there are 10 ticks per major , so each major is 1.
When I scroll through I see the value go up 0.1 at a time so all is working great.

However when I do a setInitialCurrentValue as a none whole number e.g. 200.2
it fails to scroll at all as the code does not handle these kind of values.

**Comment by kronik** [comment]
Yeah... Currently only whole values are supported. Feel free to file a pull request.

**Comment by kronik** [comment]
Ok. That was easy :) 

Fixed
