### ISSUE TITLE
Example code not correspond to current pod library 

### ISSUE THREAD

**Issue by jordanform** [kronik/ScalePicker#4]
Hi:
It's a really good development, but it seems like many properties are not available in sample code. And there are many useful properties. For example, array of values for scale, track progress etc..

**Comment by kronik** [comment]
Hi @jordanform, I just double checked and can't find any inconsistency there. Could you try to update your pod or/and give me more details?

**Comment by jordanform** [comment]
Hi: 
@kronik , here is I downloaded from pod and without member of scalepicker. I could modify myself to eliminate error but I just wanna say some of them looks like useful features. Maybe you considerate adding them back? 
    scaleView.gradientMaskEnabled = true
    scaleView.blockedUI = false
    scaleView.sidePadding = 80.0
    scaleView.title = "Speed"
    scaleView.showCurrentValue = true
    scaleView.trackProgress = true
    scaleView.invertProgress = true

scaleView.values = [32, 40, 50, 64, 80, 100, 125, 160, 200, 250, 320, 400, 500, 640, 800, 1000, 1250, 1600]

**Comment by kronik** [comment]
Not sure that I fully understand you... Last time I deleted pickerPadding size in ScalePicker. Everything else remains the same.

**Comment by jordanform** [comment]
Well, I just think that if you add some features back will be awesome. For example, defining values via array instead of min or max value....

**Comment by kronik** [comment]
This (and other features) is still there because I'm constantly using it in my own projects. Could you explain how do you configure ScalePicker and don't have "values" property? Thanks!

**Comment by jordanform** [comment]
Hi:
Just found the code where it is. The code I downloaded from the entire folder included those features. The path is ../ScalePicker-master/ScalePicker/ScalePicker.swift. However, if I do demo folder pod install the file is different from that one. Here is the version I got from terminal "Installing ScalePicker (1.1.1)" for your reference. 
Great picker, really love it. You did a really good job.

**Comment by kronik** [comment]
@jordanform Thanks for figuring this out! Let me know if you have any further questions
